### ISSUE TITLE
Problema autenticazione err. 401 Unauthorized per validazione FSE2.0

### ISSUE THREAD

**Issue by pantareisrl** [ministero-salute/it-fse-support#742]
Salve,
siamo l'azienda Pantarei Informatica Srl, e stiamo procedendo allo sviluppo delle procedure per l'accreditamento FSE2.0 ma stiamo riscontrando degli errori nel processo di validazione, potete darci supporto?
Otteniamo questa risposta a seguito della chiamata di validazione:

```yaml
{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"96c1f1c2-f749-11ee-93a7-005056ae54fa"}
```
```yaml
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  X-Backside-Transport: FAIL FAIL
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Cache-Control: no-cache, no-store, must-revalidate
  Server: GovWay-SOGEI
  Pragma: no-cache
  GovWay-Transaction-ErrorType: TokenAuthenticationFailed
  GovWay-Transaction-ID: 96c1f1c2-f749-11ee-93a7-005056ae54fa
  Date: Wed, 10 Apr 2024 15:17:30 GMT
  WWW-Authenticate: Bearer realm="FSE-JWT-Signature", error="invalid_token", error_description="Token invalid"
  Vary: *
  X-Content-Type-Options: nosniff
  X-Global-Transaction-ID: 3f7e3e2d6616ad8a00170a6d
  Expires: 0
  Content-Type: application/problem+json
}, Trailing Headers:
{
}}
```
Abbiamo analizzato i token con jwt.io e risultano entrambi "Signature Verified"

Questo è il token di Authorization Bearer:
`eyJ4NWMiOlsiTUlJRmVEQ0NBMkNnQXdJQkFnSVVJY24zYk9NeExSM3gwbG5iYVZPVXZRZC91Vjh3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBeE1qTXhNRFE1TURCYUZ3MHlOekF4TWpNeE1EUTROVGxhTUhreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNnd0pnWURWUVFEREI5VE1TTXhNVEVqVUVGT1ZFRlNSVWxKVGtaUFVrMUJWRWxEUVZOU1RGaFlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9jWFdLOVJjenpcdTAwMkI2MHQwZXYxN1lSQWVpVDhkWk12UEppaG14QjNZV3ZHeE1oSWFaVVdhRmRVZ1FGQzVzN3V5bFVIQU5tajFOb2Nta1Jkckk0bTlpUHBxSDNZc3hMc3doVUhHMjhvci9UeXQ4a0ppSFZHdi9wek9mXHUwMDJCT0gvV1hwd2t1N2FJc2hWd0toQzdxcUNYcGZhRVF2WFx1MDAyQjM3d1x1MDAyQlRZYWRYRHpucWZ6QmJZYzhPRi9TVjhvOFR5UHEyZmZnRHhsbTRDRVVNT0VLRTdYSm5ka2E0cEE2TGNIUm1wWDFRRGdQaGlKa1FjYS92UVVZMzcvTjgwcGh6TktiTGZidFBZSWpua3RqTDFFRUVIZzcvMHJ2TFR0UmJHQmYyMW1qQ2lCdEhMRWU3bWI5bmJhV2NtVkJxSno2Z2RxdGlIVzVOUkduNXNCMTAwY0dvVEp2TkJBOEV2bzR3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCUVR6dVRiaW1sa3VhdXdQOW5XMElhcFVLVkFjakFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkZhTk9kZGhyZXI1Slpab1kvS3E4dnpiREIwZjlnQnBpU2s0MDdjRGxTMUphT1kycGtiSk5ldHpUV2pOeThvQVJ5cHRFU3RmZjlXQkVGYnBtNUNGWUo5dVZGbjVaR2FKcVRcdTAwMkJQMHBGczVOZmZPWU4zemhcdTAwMkI2RzE3WWRqaGNkcnlqLzl0TDNFZ3pLV2pFVXJiOWhpZnpLb3dYRTBKbjJyc0lNQlJcdTAwMkJIaDFQSjRcdTAwMkJjRUFJTmRIYkN3a1B0N2RTNFBOYWVaUEVXMlk0UEptRVx1MDAyQjh2a0c4dllkcVllbVJxMU5pb0Y0cWFueHo3b3JPYVBLU0pERHFvclpPXHUwMDJCa0hmMGpQN2E1eWh0QWh3MHo1aUdRczRNQkU2RGllTWwyZTdcdTAwMkIwRTQxZ2tYWmpJVTRBMldkMEhsREVMdXZ6dzFXN0JSVTJiU3hhRUNTSDRBcEZaWkV3Nmlvc005OWhPM3Y3ZEFuSklPOFx1MDAyQnN4SXdIdkljSzUxa2lUYk9iZHowYlM0dU1GcE5wYk42QXlTXHUwMDJCQkVkYWgzdG9cdTAwMkI3dU9oVW5qZzFnZk1DT3hoQUhka2piSVJYZFpHWmJRSTN5VmZDUFdrMnd4c3JyL3BQZ0oxYng2TXJWWkQzeEpxb0ZQT3laRmRxY0dDV2NVR3g0Q2lwTVI0M1d4TDVJWS9SbjVVUmZRejZjSlBkRVhRVXdJUWFWWHI4QlVjVDRBMWJCdzFsc0RERXB2dVN2Q25Nb005SFx1MDAyQm1pVXZUL2p2a21qY3pBMzhnUEdERlZiZ3dBS21JMTVmL0haXHUwMDJCZzlCYU5PRG5aXHUwMDJCSDcxVW1cdTAwMkJKcGI0bUZIaU9KTndwSVY2ejVpbVBRS1FDUUppVzNqaHBVTDNyVm5ZWURrMDJTRXRJRmpkeTVid1Rld0txZHpjU254d1NQczdjcU12MHRSVzZlYzBpIl0sInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3MTI3NjIyNTAsImp0aSI6MTcxMjc2MjI1MCwiZXhwIjoxNzEyNzY1ODUwLCJpc3MiOiJhdXRoOlMxIzExMSNQQU5UQVJFSUlORk9STUFUSUNBU1JMWFgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIn0.ZZYXUsJXLHsK2gom_G_mPjWPofqd25hDluB5Ilo2lRRlxpW7QKhUOnmFW5iqYHRB1ARHDOZeaIjVDw1x4U-hnACBNT7p0HV487yO67TLeBu0pv89Do47gXOSD-mqY0ksoOFOfMdMtNftkqH8-J3jISa80Gw-Rnzs1b6pjYV7L_1sagBdMWi0cVKW8BrKZ09C4WeKaNwBwsdEqeAJ6T3NEnugIZ6sW8ZemIEP-PeIdE3K2FrZofOzaR58TBL-is1t1vlMbURWMPNjExpcO7pMILhEDCFFqQ_oV0G5I0__t3r5_pqaV3MQdHuRa8hOkBgYklmCBSCf2Mr7QI_pIcb93g`

Mentre questo è il token FSE-JWT-Signature:
`eyJ4NWMiOlsiTUlJRmVEQ0NBMkNnQXdJQkFnSVVJY24zYk9NeExSM3gwbG5iYVZPVXZRZC91Vjh3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBeE1qTXhNRFE1TURCYUZ3MHlOekF4TWpNeE1EUTROVGxhTUhreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNnd0pnWURWUVFEREI5VE1TTXhNVEVqVUVGT1ZFRlNSVWxKVGtaUFVrMUJWRWxEUVZOU1RGaFlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9jWFdLOVJjenpcdTAwMkI2MHQwZXYxN1lSQWVpVDhkWk12UEppaG14QjNZV3ZHeE1oSWFaVVdhRmRVZ1FGQzVzN3V5bFVIQU5tajFOb2Nta1Jkckk0bTlpUHBxSDNZc3hMc3doVUhHMjhvci9UeXQ4a0ppSFZHdi9wek9mXHUwMDJCT0gvV1hwd2t1N2FJc2hWd0toQzdxcUNYcGZhRVF2WFx1MDAyQjM3d1x1MDAyQlRZYWRYRHpucWZ6QmJZYzhPRi9TVjhvOFR5UHEyZmZnRHhsbTRDRVVNT0VLRTdYSm5ka2E0cEE2TGNIUm1wWDFRRGdQaGlKa1FjYS92UVVZMzcvTjgwcGh6TktiTGZidFBZSWpua3RqTDFFRUVIZzcvMHJ2TFR0UmJHQmYyMW1qQ2lCdEhMRWU3bWI5bmJhV2NtVkJxSno2Z2RxdGlIVzVOUkduNXNCMTAwY0dvVEp2TkJBOEV2bzR3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCUVR6dVRiaW1sa3VhdXdQOW5XMElhcFVLVkFjakFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkZhTk9kZGhyZXI1Slpab1kvS3E4dnpiREIwZjlnQnBpU2s0MDdjRGxTMUphT1kycGtiSk5ldHpUV2pOeThvQVJ5cHRFU3RmZjlXQkVGYnBtNUNGWUo5dVZGbjVaR2FKcVRcdTAwMkJQMHBGczVOZmZPWU4zemhcdTAwMkI2RzE3WWRqaGNkcnlqLzl0TDNFZ3pLV2pFVXJiOWhpZnpLb3dYRTBKbjJyc0lNQlJcdTAwMkJIaDFQSjRcdTAwMkJjRUFJTmRIYkN3a1B0N2RTNFBOYWVaUEVXMlk0UEptRVx1MDAyQjh2a0c4dllkcVllbVJxMU5pb0Y0cWFueHo3b3JPYVBLU0pERHFvclpPXHUwMDJCa0hmMGpQN2E1eWh0QWh3MHo1aUdRczRNQkU2RGllTWwyZTdcdTAwMkIwRTQxZ2tYWmpJVTRBMldkMEhsREVMdXZ6dzFXN0JSVTJiU3hhRUNTSDRBcEZaWkV3Nmlvc005OWhPM3Y3ZEFuSklPOFx1MDAyQnN4SXdIdkljSzUxa2lUYk9iZHowYlM0dU1GcE5wYk42QXlTXHUwMDJCQkVkYWgzdG9cdTAwMkI3dU9oVW5qZzFnZk1DT3hoQUhka2piSVJYZFpHWmJRSTN5VmZDUFdrMnd4c3JyL3BQZ0oxYng2TXJWWkQzeEpxb0ZQT3laRmRxY0dDV2NVR3g0Q2lwTVI0M1d4TDVJWS9SbjVVUmZRejZjSlBkRVhRVXdJUWFWWHI4QlVjVDRBMWJCdzFsc0RERXB2dVN2Q25Nb005SFx1MDAyQm1pVXZUL2p2a21qY3pBMzhnUEdERlZiZ3dBS21JMTVmL0haXHUwMDJCZzlCYU5PRG5aXHUwMDJCSDcxVW1cdTAwMkJKcGI0bUZIaU9KTndwSVY2ejVpbVBRS1FDUUppVzNqaHBVTDNyVm5ZWURrMDJTRXRJRmpkeTVid1Rld0txZHpjU254d1NQczdjcU12MHRSVzZlYzBpIl0sInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI1BBTlRBUkVJSU5GT1JNQVRJQ0FTUkxYWCIsImlhdCI6MTcxMjc2MjI1MCwiZXhwIjoxNzEyNzY1ODUwLCJqdGkiOjE3MTI3NjIyNTAsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlZSRE1SQzY3VDIwSTI1N0VeXl5cdTAwMjYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjJcdTAwMjZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA5MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBUb3NjYW5hIiwibG9jYWxpdHkiOiIyMDExMjM0NTYiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJSU1NNUkE3NUMwM0Y4MzlLXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy43XHUwMDI2SVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKFx1MDAyNzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMVx1MDAyNykiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJhdHRhY2htZW50X2hhc2giOiJGOUE2REVCQTJGNjk2NTU4RENBRjY5NTNGM0JEMzI5RkY5NTZBODBERDkxNjMyODhCMTU3ODE5NTdGQTlGMjk1Iiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6Ik1FRFJFUCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiUEFOVEFSRUlJTkZPUk1BVElDQVNSTCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IlYuOC4wLjAifQ.XLbK2RwsjZ0ZV6xUcmZZxVRcnEZdb0wkgyzoBGrj1vleUgJ3uWQ97Lq9MFXvYpDdrBEOvx1g1M7Lh97jcLI2CUh33qGONFkQdEHfX6F9XIJgP7lhJ9kkdMQ2wh1Zq8J55vRKDmQZDecaJtf5RxLvUt0z8mW4usqti8xxwgt8ZxaGdrvy_YxdM1hidVmaEbqaqBVeZPnZX_06Cb1eYch8WpVI7ewgYTiEZhIxqM_hKtxXLPYqUgTnqs0DK02A7wMpoUKHa5O9qHt0dr-ddK-skTu5ggK9UWlCMOSTIZzC4oCwDGdKWkQk2MUxXm5TG-5tuEjMhwb-biIJ_yCFdTp_uw`

Questo è il RequestMessage della risposta:
```yaml
{Method: POST, RequestUri: 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation', Version: 1.1, Content: System.Net.Http.MultipartFormDataContent, Headers:
{
  Accept: application/json
  Authorization: Bearer eyJ4NWMiOlsiTUlJRmVEQ0NBMkNnQXdJQkFnSVVJY24zYk9NeExSM3gwbG5iYVZPVXZRZC91Vjh3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBeE1qTXhNRFE1TURCYUZ3MHlOekF4TWpNeE1EUTROVGxhTUhreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNnd0pnWURWUVFEREI5VE1TTXhNVEVqVUVGT1ZFRlNSVWxKVGtaUFVrMUJWRWxEUVZOU1RGaFlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9jWFdLOVJjenpcdTAwMkI2MHQwZXYxN1lSQWVpVDhkWk12UEppaG14QjNZV3ZHeE1oSWFaVVdhRmRVZ1FGQzVzN3V5bFVIQU5tajFOb2Nta1Jkckk0bTlpUHBxSDNZc3hMc3doVUhHMjhvci9UeXQ4a0ppSFZHdi9wek9mXHUwMDJCT0gvV1hwd2t1N2FJc2hWd0toQzdxcUNYcGZhRVF2WFx1MDAyQjM3d1x1MDAyQlRZYWRYRHpucWZ6QmJZYzhPRi9TVjhvOFR5UHEyZmZnRHhsbTRDRVVNT0VLRTdYSm5ka2E0cEE2TGNIUm1wWDFRRGdQaGlKa1FjYS92UVVZMzcvTjgwcGh6TktiTGZidFBZSWpua3RqTDFFRUVIZzcvMHJ2TFR0UmJHQmYyMW1qQ2lCdEhMRWU3bWI5bmJhV2NtVkJxSno2Z2RxdGlIVzVOUkduNXNCMTAwY0dvVEp2TkJBOEV2bzR3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCUVR6dVRiaW1sa3VhdXdQOW5XMElhcFVLVkFjakFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkZhTk9kZGhyZXI1Slpab1kvS3E4dnpiREIwZjlnQnBpU2s0MDdjRGxTMUphT1kycGtiSk5ldHpUV2pOeThvQVJ5cHRFU3RmZjlXQkVGYnBtNUNGWUo5dVZGbjVaR2FKcVRcdTAwMkJQMHBGczVOZmZPWU4zemhcdTAwMkI2RzE3WWRqaGNkcnlqLzl0TDNFZ3pLV2pFVXJiOWhpZnpLb3dYRTBKbjJyc0lNQlJcdTAwMkJIaDFQSjRcdTAwMkJjRUFJTmRIYkN3a1B0N2RTNFBOYWVaUEVXMlk0UEptRVx1MDAyQjh2a0c4dllkcVllbVJxMU5pb0Y0cWFueHo3b3JPYVBLU0pERHFvclpPXHUwMDJCa0hmMGpQN2E1eWh0QWh3MHo1aUdRczRNQkU2RGllTWwyZTdcdTAwMkIwRTQxZ2tYWmpJVTRBMldkMEhsREVMdXZ6dzFXN0JSVTJiU3hhRUNTSDRBcEZaWkV3Nmlvc005OWhPM3Y3ZEFuSklPOFx1MDAyQnN4SXdIdkljSzUxa2lUYk9iZHowYlM0dU1GcE5wYk42QXlTXHUwMDJCQkVkYWgzdG9cdTAwMkI3dU9oVW5qZzFnZk1DT3hoQUhka2piSVJYZFpHWmJRSTN5VmZDUFdrMnd4c3JyL3BQZ0oxYng2TXJWWkQzeEpxb0ZQT3laRmRxY0dDV2NVR3g0Q2lwTVI0M1d4TDVJWS9SbjVVUmZRejZjSlBkRVhRVXdJUWFWWHI4QlVjVDRBMWJCdzFsc0RERXB2dVN2Q25Nb005SFx1MDAyQm1pVXZUL2p2a21qY3pBMzhnUEdERlZiZ3dBS21JMTVmL0haXHUwMDJCZzlCYU5PRG5aXHUwMDJCSDcxVW1cdTAwMkJKcGI0bUZIaU9KTndwSVY2ejVpbVBRS1FDUUppVzNqaHBVTDNyVm5ZWURrMDJTRXRJRmpkeTVid1Rld0txZHpjU254d1NQczdjcU12MHRSVzZlYzBpIl0sInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3MTI3NjIyNTAsImp0aSI6MTcxMjc2MjI1MCwiZXhwIjoxNzEyNzY1ODUwLCJpc3MiOiJhdXRoOlMxIzExMSNQQU5UQVJFSUlORk9STUFUSUNBU1JMWFgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIn0.ZZYXUsJXLHsK2gom_G_mPjWPofqd25hDluB5Ilo2lRRlxpW7QKhUOnmFW5iqYHRB1ARHDOZeaIjVDw1x4U-hnACBNT7p0HV487yO67TLeBu0pv89Do47gXOSD-mqY0ksoOFOfMdMtNftkqH8-J3jISa80Gw-Rnzs1b6pjYV7L_1sagBdMWi0cVKW8BrKZ09C4WeKaNwBwsdEqeAJ6T3NEnugIZ6sW8ZemIEP-PeIdE3K2FrZofOzaR58TBL-is1t1vlMbURWMPNjExpcO7pMILhEDCFFqQ_oV0G5I0__t3r5_pqaV3MQdHuRa8hOkBgYklmCBSCf2Mr7QI_pIcb93g
  FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmVEQ0NBMkNnQXdJQkFnSVVJY24zYk9NeExSM3gwbG5iYVZPVXZRZC91Vjh3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBeE1qTXhNRFE1TURCYUZ3MHlOekF4TWpNeE1EUTROVGxhTUhreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNnd0pnWURWUVFEREI5VE1TTXhNVEVqVUVGT1ZFRlNSVWxKVGtaUFVrMUJWRWxEUVZOU1RGaFlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9jWFdLOVJjenpcdTAwMkI2MHQwZXYxN1lSQWVpVDhkWk12UEppaG14QjNZV3ZHeE1oSWFaVVdhRmRVZ1FGQzVzN3V5bFVIQU5tajFOb2Nta1Jkckk0bTlpUHBxSDNZc3hMc3doVUhHMjhvci9UeXQ4a0ppSFZHdi9wek9mXHUwMDJCT0gvV1hwd2t1N2FJc2hWd0toQzdxcUNYcGZhRVF2WFx1MDAyQjM3d1x1MDAyQlRZYWRYRHpucWZ6QmJZYzhPRi9TVjhvOFR5UHEyZmZnRHhsbTRDRVVNT0VLRTdYSm5ka2E0cEE2TGNIUm1wWDFRRGdQaGlKa1FjYS92UVVZMzcvTjgwcGh6TktiTGZidFBZSWpua3RqTDFFRUVIZzcvMHJ2TFR0UmJHQmYyMW1qQ2lCdEhMRWU3bWI5bmJhV2NtVkJxSno2Z2RxdGlIVzVOUkduNXNCMTAwY0dvVEp2TkJBOEV2bzR3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCUVR6dVRiaW1sa3VhdXdQOW5XMElhcFVLVkFjakFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkZhTk9kZGhyZXI1Slpab1kvS3E4dnpiREIwZjlnQnBpU2s0MDdjRGxTMUphT1kycGtiSk5ldHpUV2pOeThvQVJ5cHRFU3RmZjlXQkVGYnBtNUNGWUo5dVZGbjVaR2FKcVRcdTAwMkJQMHBGczVOZmZPWU4zemhcdTAwMkI2RzE3WWRqaGNkcnlqLzl0TDNFZ3pLV2pFVXJiOWhpZnpLb3dYRTBKbjJyc0lNQlJcdTAwMkJIaDFQSjRcdTAwMkJjRUFJTmRIYkN3a1B0N2RTNFBOYWVaUEVXMlk0UEptRVx1MDAyQjh2a0c4dllkcVllbVJxMU5pb0Y0cWFueHo3b3JPYVBLU0pERHFvclpPXHUwMDJCa0hmMGpQN2E1eWh0QWh3MHo1aUdRczRNQkU2RGllTWwyZTdcdTAwMkIwRTQxZ2tYWmpJVTRBMldkMEhsREVMdXZ6dzFXN0JSVTJiU3hhRUNTSDRBcEZaWkV3Nmlvc005OWhPM3Y3ZEFuSklPOFx1MDAyQnN4SXdIdkljSzUxa2lUYk9iZHowYlM0dU1GcE5wYk42QXlTXHUwMDJCQkVkYWgzdG9cdTAwMkI3dU9oVW5qZzFnZk1DT3hoQUhka2piSVJYZFpHWmJRSTN5VmZDUFdrMnd4c3JyL3BQZ0oxYng2TXJWWkQzeEpxb0ZQT3laRmRxY0dDV2NVR3g0Q2lwTVI0M1d4TDVJWS9SbjVVUmZRejZjSlBkRVhRVXdJUWFWWHI4QlVjVDRBMWJCdzFsc0RERXB2dVN2Q25Nb005SFx1MDAyQm1pVXZUL2p2a21qY3pBMzhnUEdERlZiZ3dBS21JMTVmL0haXHUwMDJCZzlCYU5PRG5aXHUwMDJCSDcxVW1cdTAwMkJKcGI0bUZIaU9KTndwSVY2ejVpbVBRS1FDUUppVzNqaHBVTDNyVm5ZWURrMDJTRXRJRmpkeTVid1Rld0txZHpjU254d1NQczdjcU12MHRSVzZlYzBpIl0sInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI1BBTlRBUkVJSU5GT1JNQVRJQ0FTUkxYWCIsImlhdCI6MTcxMjc2MjI1MCwiZXhwIjoxNzEyNzY1ODUwLCJqdGkiOjE3MTI3NjIyNTAsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlZSRE1SQzY3VDIwSTI1N0VeXl5cdTAwMjYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjJcdTAwMjZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA5MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBUb3NjYW5hIiwibG9jYWxpdHkiOiIyMDExMjM0NTYiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJSU1NNUkE3NUMwM0Y4MzlLXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy43XHUwMDI2SVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKFx1MDAyNzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMVx1MDAyNykiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJhdHRhY2htZW50X2hhc2giOiJGOUE2REVCQTJGNjk2NTU4RENBRjY5NTNGM0JEMzI5RkY5NTZBODBERDkxNjMyODhCMTU3ODE5NTdGQTlGMjk1Iiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6Ik1FRFJFUCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiUEFOVEFSRUlJTkZPUk1BVElDQVNSTCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IlYuOC4wLjAifQ.XLbK2RwsjZ0ZV6xUcmZZxVRcnEZdb0wkgyzoBGrj1vleUgJ3uWQ97Lq9MFXvYpDdrBEOvx1g1M7Lh97jcLI2CUh33qGONFkQdEHfX6F9XIJgP7lhJ9kkdMQ2wh1Zq8J55vRKDmQZDecaJtf5RxLvUt0z8mW4usqti8xxwgt8ZxaGdrvy_YxdM1hidVmaEbqaqBVeZPnZX_06Cb1eYch8WpVI7ewgYTiEZhIxqM_hKtxXLPYqUgTnqs0DK02A7wMpoUKHa5O9qHt0dr-ddK-skTu5ggK9UWlCMOSTIZzC4oCwDGdKWkQk2MUxXm5TG-5tuEjMhwb-biIJ_yCFdTp_uw
  Content-Type: multipart/form-data; boundary="4d15353a-356f-42b0-b7d6-cc465068494d"
  Content-Length: 9938
}}
```

Grazie per il supporto.
